name: demo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.7.4=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.32.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - cattrs==23.2.3
    - charset-normalizer==3.3.2
    - click==8.1.7
    - datasets==2.20.0
    - deepspeed==0.14.4
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - exceptiongroup==1.2.1
    - filelock==3.15.4
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - hjson==3.1.0
    - huggingface-hub==0.23.4
    - idna==3.7
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.1
    - ninja==1.11.1.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.555.43
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu12==12.1.105
    - packaging==24.1
    - pandas==2.0.3
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - protobuf==5.27.2
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pygments==2.18.0
    - python-dateutil==2.9.0.post0
    - python-rapidjson==1.18
    - pytz==2024.1
    - pyyaml==6.0.1
    - ray==2.10.0
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - rpds-py==0.19.0
    - safetensors==0.4.3
    - sentry-sdk==2.8.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.13.0
    - tabulate==0.9.0
    - tokenizers==0.19.1
    - torch==2.3.1
    - torchtyping==0.1.4
    - tqdm==4.66.4
    - transformers==4.42.3
    - triton==2.3.1
    - tritonclient==2.47.0
    - trlx==0.7.0
    - typeguard==4.3.0
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - wandb==0.17.4
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.19.2
prefix: /scratch/x2889a02/.conda/envs/demo
